### ISSUE TITLE
No Point feature when for the hfradar wedges

### ISSUE THREAD

**Issue by ocefpaf** [SECOORA/static_assets#1]
This logic [here](https://github.com/SECOORA/static_assets/blob/master/hfradar/convert.py#L129-L140) will create a `Point` feature only when there is no `wedge` in the HF-Radar spreadsheet. See the rendered [GeoJSON](https://github.com/SECOORA/static_assets/blob/master/hfradar/hfradar.geojson) for an example.

@kwilcox I believe this is a bug. Correct?  If that is by design I can find another way to add the hfradar icon together with the wedge shape.  If not let me know and I can send a PR to fix it.

**Comment by kwilcox** [comment]
I did that on purpose, but I can see why someone would want a point when there is a wedge as well

**Comment by ocefpaf** [comment]
> I did that on purpose

That is fine.  I do not want to mess up your workflow.

> but I can see why someone would want a point when there is a wedge as well.

I use the GeoJSON and its metadata to create my folium version of the map.  @vembus mentioned he will need a map soon for a propoasal and I just want to be ready for it :wink:
