### ISSUE TITLE
Glider tracks

### ISSUE THREAD

**Issue by ocefpaf** [SECOORA/static_assets#13]
@kwilcox the glider [tracks](https://github.com/SECOORA/static_assets/blob/master/glider_tracks/README.md#secoora-glider-tracks) are actually just two triangles.  I cannot find the tracks plotted on [this](https://github.com/SECOORA/static_assets/blob/master/maps/assets.png).

@vembus do you have any other source data for these tracks?

**Comment by kwilcox** [comment]
They are the faint thick black triangles, one south of Core Banks and one east of Gray's Reef.

I was given a PNG image and had someone trace the triangles manually to get them into a GIS format.

**Comment by ocefpaf** [comment]
> They are the faint thick black triangles, one south of Core Banks and one east of Gray's Reef.

OK.  I got them as geojson too (#12) and they are showing on my map now:

http://nbviewer.ipython.org/github/SECOORA/static_assets/blob/master/make_map.ipynb

> I was given a PNG image and had someone trace the triangles manually to get them into a GIS format.

Got it.  Thanks!  But do we have these track lines:

![tracks](https://cloud.githubusercontent.com/assets/950575/12175436/02a2d5de-b541-11e5-9ec5-06e51bb7962f.png)

**Comment by kwilcox** [comment]
Those were also traced manually... here is the ZIP

[gliders_from_georefd.zip](https://github.com/SECOORA/static_assets/files/81384/gliders_from_georefd.zip)

**Comment by ocefpaf** [comment]
Thanks!  I will add that to the `glider_tracks directory`.
